### ISSUE TITLE
 Error while training CANNET

### ISSUE THREAD

**Issue by MagazzuGaetano** [gjy3035/NWPU-Crowd-Sample-Code#14]
[NWPU DATASET]: 3109 training images.
[NWPU DATASET]: 500 validation images.
dataset preparation finished!
training has started!
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2973: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1569: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:432: UserWarning: Using a target size (torch.Size([4, 576, 768])) that is different to the input size (torch.Size([4, 72, 96])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    cc_trainer.forward()
  File "/content/drive/My Drive/Stage Crowd Counting/NPWU-CROWD/trainer.py", line 66, in forward
    self.train()
  File "/content/drive/My Drive/Stage Crowd Counting/NPWU-CROWD/trainer.py", line 102, in train
    pred_map, _ = self.net(img, gt_map)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Stage Crowd Counting/NPWU-CROWD/models/CC.py", line 35, in forward
    self.loss_mse= self.build_loss(density_map.squeeze(), gt_map.squeeze())               
  File "/content/drive/My Drive/Stage Crowd Counting/NPWU-CROWD/models/CC.py", line 39, in build_loss
    loss_mse = self.loss_mse_fn(density_map, gt_data)  
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 432, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2542, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 62, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)
RuntimeError: The size of tensor a (96) must match the size of tensor b (768) at non-singleton dimension 2

**Comment by xiaomeng654321** [comment]
@MagazzuGaetano how to change the network when training, the config of MCNN is default loaded

**Comment by msn199959** [comment]
I have the same question, how to solve it?
