### ISSUE TITLE
RuntimeError: unexpected EOF in python test.py

### ISSUE THREAD

**Issue by aliraza0769** [gjy3035/NWPU-Crowd-Sample-Code#21]
we encountered runtime error when we simulated the below code line 
!python test.py.

The following has been encountered

Traceback (most recent call last):
  File "test.py", line 118, in <module>
    main()
  File "test.py", line 46, in main
    test(lines, model_path)
  File "test.py", line 55, in test
    net.load_state_dict(torch.load(model_path))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 779, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 3302200 more bytes. The file might be corrupted.

**Comment by Elin24** [comment]
The state_dict (model_path) file might be corrupted.
