### ISSUE TITLE
Problem in training

### ISSUE THREAD

**Issue by Nemasery** [gjy3035/NWPU-Crowd-Sample-Code#4]
[ep 1][it 80][loss 0.0043][lr 1.0000][0.71s]
        [cnt: gt: 155.0 pred: 0.03]
[ep 1][it 90][loss 0.0047][lr 1.0000][0.72s]
        [cnt: gt: 10.0 pred: 0.29]
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    cc_trainer.forward()
  File "/root/ljh/NWPU-Crowd-Sample-Code/trainer.py", line 63, in forward
    self.train()
  File "/root/ljh/NWPU-Crowd-Sample-Code/trainer.py", line 82, in train
    for i, data in enumerate(self.train_loader, 0):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 310, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/ljh/NWPU-Crowd-Sample-Code/datasets/basedataset.py", line 57, in __getitem__
    img = self.img_transform(img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py", line 217, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

**Comment by gjy3035** [comment]
Is this error re-produced?
